// =======================================================================
// COMPREHENSIVE DATASET OF CAFES ACROSS ALL 14 DISTRICTS OF KOSHI PROVINCE
// (Eastern Nepal), featuring an exhaustive list of Birtamod cafes.
// =======================================================================

const KOSHI_CAFES = [
  // =====================================================================
  // 1. JHAPA DISTRICT - BIRTAMOD (Exhaustive & Complete Collection)
  // =====================================================================
  {
    id: "birt-brikshya",
    name: "Brikshya Café & Lounge",
    city: "Birtamod",
    district: "Jhapa",
    area: "Mukti Chowk & Durgapur",
    lat: 26.6345,
    lng: 87.9860,
    rating: 4.9,
    reviewsCount: 580,
    priceLevel: "रुरु",
    vibe: ["Aesthetic & Cozy", "Specialty Coffee", "Weekend Hangout / Live Vibe"],
    features: ["Botanical Sanctuary", "Wood-fire Pizza", "Fast WiFi", "Cocktail Bar", "Live Weekend Sessions"],
    signatureItem: "Cold Brew Tonic & Coconut Milk Latte",
    foodHighlight: "Neapolitan Wood-Fired Pizza & Peri Peri Chicken",
    weekendTip: "Jhapa's top weekend hotspot! Reserve an evening booth surrounded by tropical plants with live acoustic music.",
    timing: "8:00 AM – 10:00 PM",
    phone: "+977 23-543210",
    instagram: "@brikshyacafe",
    image: "https://images.unsplash.com/photo-1493857671505-72967e2e2760?auto=format&fit=crop&w=800&q=80",
    description: "An extraordinary lush urban oasis in Birtamod filled with hanging tropical greenery, artisanal specialty brews, and authentic wood-fired pizzas."
  },
  {
    id: "birt-mimiz",
    name: "Mimiz Cafe",
    city: "Birtamod",
    district: "Jhapa",
    area: "Bhadrapur Road, Birtamod",
    lat: 26.6310,
    lng: 87.9890,
    rating: 4.8,
    reviewsCount: 340,
    priceLevel: "रुरु",
    vibe: ["Aesthetic & Cozy", "Bakery & Desserts"],
    features: ["Plant-based Options", "Pastry Counter", "Aesthetic Pastel Decor", "Fast WiFi", "AC"],
    signatureItem: "Matcha Espresso Fusion & Belgian Hot Chocolate",
    foodHighlight: "Vegan Dark Chocolate Truffle Cake & Avocado Toast",
    weekendTip: "The most serene, pastel-toned cafe in Birtamod for brunch and aesthetically pleasing weekend photos.",
    timing: "8:30 AM – 9:00 PM",
    phone: "+977 9801123445",
    instagram: "@mimizcafe",
    image: "https://images.unsplash.com/photo-1497636577773-f1231844b336?auto=format&fit=crop&w=800&q=80",
    description: "Celebrated for its modern botanical decor, artisan desserts, plant-rich wholesome brunch recipes, and thoughtful barista craft."
  },
  {
    id: "birt-kyles",
    name: "Kyle’s Café",
    city: "Birtamod",
    district: "Jhapa",
    area: "Sanischare Road, Birtamod",
    lat: 26.6390,
    lng: 87.9855,
    rating: 4.7,
    reviewsCount: 290,
    priceLevel: "रुरु",
    vibe: ["Weekend Hangout / Live Vibe", "Bakery & Desserts"],
    features: ["Trendy Interior", "Artisan Bakery", "AC", "WiFi"],
    signatureItem: "Iced Caramel Macchiato & Signature Nitro Brew",
    foodHighlight: "Gourmet Chicken Burgers & Waffles with Maple Syrup",
    weekendTip: "Super popular among young crowds on Saturday afternoons for crispy burgers and milkshakes.",
    timing: "9:00 AM – 9:30 PM",
    phone: "+977 23-541299",
    instagram: "@kylescafe_birtamod",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    description: "Chic, urban industrial cafe along Sanischare Road offering decadent bakery items, specialty coffee, and savory weekend bites."
  },
  {
    id: "birt-brewedbook",
    name: "The Brewed Book Cafe",
    city: "Birtamod",
    district: "Jhapa",
    area: "Central Birtamod",
    lat: 26.6335,
    lng: 87.9870,
    rating: 4.7,
    reviewsCount: 215,
    priceLevel: "रुरु",
    vibe: ["Work & Study Friendly", "Aesthetic & Cozy", "Specialty Coffee"],
    features: ["Book Library", "Quiet Reading Nooks", "Power Sockets", "WiFi"],
    signatureItem: "Pour-over Himalayan Drip & Hazelnut Latte",
    foodHighlight: "Grilled Panini & Homemade Blueberry Muffins",
    weekendTip: "Pick a classic novel from their wooden bookshelf and enjoy peaceful hours with freshly brewed coffee.",
    timing: "8:00 AM – 8:30 PM",
    phone: "+977 9804455667",
    instagram: "@thebrewedbookcafe",
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    description: "A dream sanctuary for bibliophiles and quiet souls. Floor-to-ceiling bookshelves, warm amber lighting, and rich organic coffee."
  },
  {
    id: "birt-ganapati",
    name: "Ganapati’s The Cafe & Bakery",
    city: "Birtamod",
    district: "Jhapa",
    area: "Mukti Chowk South, Birtamod",
    lat: 26.6320,
    lng: 87.9835,
    rating: 4.6,
    reviewsCount: 380,
    priceLevel: "रु",
    vibe: ["Bakery & Desserts", "Weekend Hangout / Live Vibe"],
    features: ["Fresh Bakery Counter", "Custom Cakes", "Fast Service", "Family Seating"],
    signatureItem: "Classic Cappuccino & Creamy Cold Coffee",
    foodHighlight: "Freshly Baked Black Forest Pastries & Veg Patties",
    weekendTip: "Grab their hot morning bakery batch right as the doors open at 8 AM for unbeatable freshness.",
    timing: "7:30 AM – 9:00 PM",
    phone: "+977 23-542018",
    instagram: "@ganapaticafebirtamod",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    description: "A staple in Birtamod known for decades of artisan baking excellence, decadent cream cakes, and reliable, warm coffee."
  },
  {
    id: "birt-firewood",
    name: "Firewood Bakery and Cafe",
    city: "Birtamod",
    district: "Jhapa",
    area: "Bhadrapur Road, Birtamod",
    lat: 26.6305,
    lng: 87.9880,
    rating: 4.6,
    reviewsCount: 260,
    priceLevel: "रुरु",
    vibe: ["Bakery & Desserts", "Aesthetic & Cozy"],
    features: ["Wood-fired Oven", "Artisanal Breads", "WiFi", "Pastry Bar"],
    signatureItem: "Flavored Mocha & Irish Cream Iced Latte",
    foodHighlight: "Wood-fired Sourdough Pizza & Croissants",
    weekendTip: "Try their fresh sourdough loaves and crusty wood-fired baguettes on Saturday mornings.",
    timing: "8:00 AM – 9:30 PM",
    phone: "+977 23-544567",
    instagram: "@firewood_birtamod",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80",
    description: "Bringing rustic hearth baking to Birtamod with authentic firewood ovens, European breads, and aromatic espresso drinks."
  },
  {
    id: "birt-greens",
    name: "The Green's Café",
    city: "Birtamod",
    district: "Jhapa",
    area: "Near Bus Park, Birtamod",
    lat: 26.6370,
    lng: 87.9810,
    rating: 4.6,
    reviewsCount: 240,
    priceLevel: "रुरु",
    vibe: ["Aesthetic & Cozy", "Work & Study Friendly"],
    features: ["Garden Courtyard", "Organic Menu", "WiFi", "Quiet Corner"],
    signatureItem: "Iced Green Tea Lemonade & Flat White",
    foodHighlight: "Farm-Fresh Greek Salad & Grilled Chicken Wrap",
    weekendTip: "Relax in their tranquil courtyard garden for a leisurely Sunday detox with fresh juices and light bites.",
    timing: "8:00 AM – 8:30 PM",
    phone: "+977 23-541188",
    instagram: "@thegreenscafe_birtamod",
    image: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=800&q=80",
    description: "A serene courtyard retreat providing fresh organic ingredients, farm-to-table snacks, and a calming escape from city traffic."
  },
  {
    id: "birt-lungma",
    name: "Lungma Cafe & Restaurant",
    city: "Birtamod",
    district: "Jhapa",
    area: "Mukti Chowk East, Birtamod",
    lat: 26.6350,
    lng: 87.9895,
    rating: 4.5,
    reviewsCount: 310,
    priceLevel: "रु",
    vibe: ["Weekend Hangout / Live Vibe"],
    features: ["Tibetan & Continental", "Spacious Hall", "WiFi", "Momo Specials"],
    signatureItem: "Spiced Hot Milk Coffee & Mint Lemonade",
    foodHighlight: "Steamed Kothey Momo & Creamy White Sauce Pasta",
    weekendTip: "Known for the juiciest momos in town paired with budget-friendly chilled beverages.",
    timing: "9:30 AM – 9:30 PM",
    phone: "+977 23-540987",
    instagram: "@lungmacafe_birtamod",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    description: "Spacious and lively local favorite offering delectable Tibetan bites, pastas, and family-style weekend dining."
  },
  {
    id: "birt-purwanchalbakery",
    name: "Purwanchal Bakery and Cafe",
    city: "Birtamod",
    district: "Jhapa",
    area: "Hanuman Central Mall, Birtamod",
    lat: 26.6330,
    lng: 87.9850,
    rating: 4.5,
    reviewsCount: 220,
    priceLevel: "रु",
    vibe: ["Bakery & Desserts", "Work & Study Friendly"],
    features: ["Mall Complex", "Air Conditioned", "Quick Service", "Dessert Counter"],
    signatureItem: "Spanish Latte & Choco Frappe",
    foodHighlight: "Red Velvet Pastry & Chicken Patties",
    weekendTip: "The ideal pitstop for a refreshing coffee break after shopping at Hanuman Central.",
    timing: "9:00 AM – 9:00 PM",
    phone: "+977 23-545678",
    instagram: "@purwanchal_hanumancentral",
    image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=800&q=80",
    description: "Conveniently located inside Hanuman Central with premium bakery creations, chilled frappes, and cool AC seating."
  },
  {
    id: "birt-foodmood",
    name: "Food Mood Cafe",
    city: "Birtamod",
    district: "Jhapa",
    area: "Mukti Chowk West, Birtamod",
    lat: 26.6330,
    lng: 87.9840,
    rating: 4.5,
    reviewsCount: 290,
    priceLevel: "रु",
    vibe: ["Weekend Hangout / Live Vibe"],
    features: ["Budget Friendly", "Pop Music", "Quick Bites", "WiFi"],
    signatureItem: "KitKat Thick Shake & Hazelnut Iced Coffee",
    foodHighlight: "Crispy Burgers & Loaded Cheesy Fries",
    weekendTip: "Energetic hangout packed with vibrant energy, music, and finger-licking burgers for Saturday afternoon get-togethers.",
    timing: "9:30 AM – 9:30 PM",
    phone: "+977 9803332211",
    instagram: "@foodmood_birtamod",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    description: "Vibrant casual destination buzzing with lively beats, youthful energy, decadent monster shakes, and comforting snacks."
  },
  {
    id: "birt-layana",
    name: "Layana Bistro & Cafe",
    city: "Birtamod",
    district: "Jhapa",
    area: "Hospital Line / Birtamod",
    lat: 26.6360,
    lng: 87.9865,
    rating: 4.7,
    reviewsCount: 310,
    priceLevel: "रुरु",
    vibe: ["Aesthetic & Cozy", "Weekend Hangout / Live Vibe"],
    features: ["Bistro Atmosphere", "Fine Plating", "Mocktail Lounge", "WiFi"],
    signatureItem: "Espresso Tonic & Rose Berry Mojito",
    foodHighlight: "Herb Roasted Chicken & Thin Crust Pizza",
    weekendTip: "Sophisticated venue for evening weekend dates with soft lighting and contemporary fusion dining.",
    timing: "10:00 AM – 10:00 PM",
    phone: "+977 23-546123",
    instagram: "@layanabistro",
    image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80",
    description: "A premier bistro lounge in Birtamod serving artisanal coffee, gourmet European plates, and handcrafted weekend coolers."
  },

  // =====================================================================
  // 1. JHAPA DISTRICT - DAMAK & OTHER HUBS
  // =====================================================================
  {
    id: "damak-oisi",
    name: "Oisi Coffee House & Food Trails",
    city: "Damak",
    district: "Jhapa",
    area: "Thana Road, Damak",
    lat: 26.6665,
    lng: 87.6950,
    rating: 4.8,
    reviewsCount: 380,
    priceLevel: "रुरु",
    vibe: ["Specialty Coffee", "Bakery & Desserts", "Aesthetic & Cozy"],
    features: ["Artisan Roasts", "Decadent Desserts", "WiFi", "AC"],
    signatureItem: "Signature Oisi Iced Latte & Aeropress Special",
    foodHighlight: "Tiramisu Cups & Gourmet Club Sandwiches",
    weekendTip: "Try their weekend special dessert platter paired with high-elevation organic coffee.",
    timing: "7:30 AM – 9:00 PM",
    phone: "+977 23-580999",
    instagram: "@oisicoffee_damak",
    image: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?auto=format&fit=crop&w=800&q=80",
    description: "The crown jewel of Damak's cafe culture. Praised for exceptional presentation, velvety espressos, and authentic Italian tiramisu."
  },
  {
    id: "damak-mycafe",
    name: "Mycafe Barista Academy & Lounge",
    city: "Damak",
    district: "Jhapa",
    area: "Damak Chowk South",
    lat: 26.6640,
    lng: 87.6920,
    rating: 4.7,
    reviewsCount: 310,
    priceLevel: "रुरु",
    vibe: ["Specialty Coffee", "Work & Study Friendly"],
    features: ["Barista Training Hub", "Manual Brews", "WiFi", "Quiet Corners"],
    signatureItem: "V60 Single Origin Pourover & Swan Latte Art",
    foodHighlight: "Grilled Chicken Panini & Brownie with Gelato",
    weekendTip: "Talk with professional baristas about roast profiles and coffee origin stories while they craft your drink.",
    timing: "7:00 AM – 8:30 PM",
    phone: "+977 23-582100",
    instagram: "@mycafedamak",
    image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=800&q=80",
    description: "A hub where coffee craftsmanship meets passion. They train aspiring baristas and serve precision-extracted artisan coffee."
  },
  {
    id: "damak-reef",
    name: "Reef Cafe & Restaurant",
    city: "Damak",
    district: "Jhapa",
    area: "Beldangi Road, Damak",
    lat: 26.6710,
    lng: 87.6980,
    rating: 4.6,
    reviewsCount: 270,
    priceLevel: "रुरु",
    vibe: ["Weekend Hangout / Live Vibe", "Aesthetic & Cozy"],
    features: ["Modern Interior", "Private Dining Booths", "Mocktails & Coffee", "WiFi"],
    signatureItem: "Blue Lagoon Mocktail & Caramel Frappe",
    foodHighlight: "Crispy Honey Chilly Potato & Sizzling Momos",
    weekendTip: "Great for weekend dinner dates and lively friend groups looking for upscale lighting and upbeat tunes.",
    timing: "9:00 AM – 9:30 PM",
    phone: "+977 9814455667",
    instagram: "@reefcafedamak",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    description: "Sleek, contemporary venue in Damak offering fusion dining, inventive mocktails, and decadent espresso concoctions."
  },
  {
    id: "jhapa-kakarbhitta",
    name: "Border Gate Coffee & Restro",
    city: "Kakarbhitta",
    district: "Jhapa",
    area: "Nepal-India Border Point, Kakarbhitta",
    lat: 26.6500,
    lng: 88.1600,
    rating: 4.5,
    reviewsCount: 190,
    priceLevel: "रु",
    vibe: ["Weekend Hangout / Live Vibe"],
    features: ["Border Crossing View", "Traveler Friendly", "Tea & Coffee Bar"],
    signatureItem: "Darjeeling First Flush & Strong Espresso",
    foodHighlight: "Hot Samosas & Nepali Khaja Plate",
    weekendTip: "Great transit cafe right where Nepal meets India; sip high-grade tea watching border life unfold.",
    timing: "6:30 AM – 8:30 PM",
    phone: "+977 23-562111",
    instagram: "@kakarbhittacafe",
    image: "https://images.unsplash.com/photo-1525610553991-2bede1a236e2?auto=format&fit=crop&w=800&q=80",
    description: "The gateway cafe of Eastern Nepal in Kakarbhitta, popular with international overland travelers and cross-border shoppers."
  },

  // =====================================================================
  // 2. MORANG DISTRICT (Biratnagar, Belbari, Urlabari)
  // =====================================================================
  {
    id: "brt-wakecup",
    name: "WakeCup Coffee",
    city: "Biratnagar",
    district: "Morang",
    area: "Tintoliya / Main Road",
    lat: 26.4525,
    lng: 87.2798,
    rating: 4.8,
    reviewsCount: 510,
    priceLevel: "रुरु",
    vibe: ["Specialty Coffee", "Work & Study Friendly", "Aesthetic & Cozy"],
    features: ["Artisan Roasts", "High-Speed WiFi", "Charging Ports", "Quiet Study Zone"],
    signatureItem: "Cortado, Flat White & Chemex Drip",
    foodHighlight: "New York Style Cheesecake & Smoked Chicken Panini",
    weekendTip: "The ultimate haven for remote workers, tech builders, and coffee geeks needing focused, calm energy on Saturdays.",
    timing: "7:00 AM – 9:00 PM",
    phone: "+977 21-460111",
    instagram: "@wakecupcoffeene",
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80",
    description: "The trailblazer of specialty third-wave coffee in Biratnagar. Exceptional baristas extracting notes of citrus and chocolate from high-altitude beans."
  },
  {
    id: "brt-ono",
    name: "Ono Cafe",
    city: "Biratnagar",
    district: "Morang",
    area: "Traffic Chowk",
    lat: 26.4580,
    lng: 87.2810,
    rating: 4.7,
    reviewsCount: 340,
    priceLevel: "रुरु",
    vibe: ["Aesthetic & Cozy", "Bakery & Desserts"],
    features: ["Insta-worthy Interiors", "Bakery", "AC", "WiFi"],
    signatureItem: "Lotus Biscoff Frappe & Velvet Mocha",
    foodHighlight: "Fresh Cinnamon Rolls & Truffle Fries",
    weekendTip: "Aesthetic beige minimalist backdrop makes this the #1 photography and date-spot in town.",
    timing: "8:00 AM – 9:30 PM",
    phone: "+977 9801239876",
    instagram: "@onocafe_brt",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    description: "Sleek Japandi-inspired aesthetics meet delectable bakery goods and handcrafted artisanal beverages in the heart of Biratnagar."
  },
  {
    id: "brt-citrus",
    name: "Citrus Café at Lemon Tree",
    city: "Biratnagar",
    district: "Morang",
    area: "Premier Hotel, Central Biratnagar",
    lat: 26.4650,
    lng: 87.2825,
    rating: 4.7,
    reviewsCount: 280,
    priceLevel: "रururu",
    vibe: ["Aesthetic & Cozy", "Bakery & Desserts"],
    features: ["Luxury Ambience", "Valet Parking", "Buffet Options", "Fine Dining"],
    signatureItem: "Espresso Romano & Darjeeling First Flush",
    foodHighlight: "Gourmet Club Sandwiches & Artisanal Pastries",
    weekendTip: "Best suited for an upscale weekend family brunch or formal business rendezvous in air-conditioned elegance.",
    timing: "6:30 AM – 10:30 PM",
    phone: "+977 21-577777",
    instagram: "@lemontreebiratnagar",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80",
    description: "High-end multi-cuisine cafe set within Lemon Tree Premier, offering world-class hospitality, immaculate presentation, and quiet luxury."
  },
  {
    id: "brt-roadside",
    name: "Roadside Cafe Nepal",
    city: "Biratnagar",
    district: "Morang",
    area: "Hospital Chowk",
    lat: 26.4610,
    lng: 87.2750,
    rating: 4.5,
    reviewsCount: 390,
    priceLevel: "रु",
    vibe: ["Weekend Hangout / Live Vibe"],
    features: ["Affordable", "Local Legend", "Casual", "Outdoor Vibe"],
    signatureItem: "Classic Sweet Milk Coffee & Iced Lemon Tea",
    foodHighlight: "Juicy Buff Momo & Crispy C-Momo",
    weekendTip: "Never leave without ordering their signature steaming momo plate alongside chilled coffee.",
    timing: "9:00 AM – 9:00 PM",
    phone: "+977 9842055667",
    instagram: "@roadsidecafebir",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    description: "A staple Biratnagar hangout renowned for authentic local flavors, rapid service, and relaxed camaraderie among friends."
  },
  {
    id: "morang-urlabari",
    name: "Royal Coffee & Restro",
    city: "Urlabari",
    district: "Morang",
    area: "Urlabari Chowk",
    lat: 26.6730,
    lng: 87.6250,
    rating: 4.6,
    reviewsCount: 195,
    priceLevel: "रु",
    vibe: ["Weekend Hangout / Live Vibe"],
    features: ["Family Friendly", "Highway Stop", "WiFi"],
    signatureItem: "Iced Mocha & Cold Coffee",
    foodHighlight: "Chicken Sekuwa & Steamed Momos",
    weekendTip: "Popular pitstop along the East-West Highway connecting Jhapa and Morang.",
    timing: "8:00 AM – 9:30 PM",
    phone: "+977 21-571234",
    instagram: "@royalcafe_urlabari",
    image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80",
    description: "A welcoming gathering spot in Urlabari offering chilled coffees, sizzling momos, and comfortable booths."
  },

  // =====================================================================
  // 3. SUNSARI DISTRICT (Dharan & Itahari)
  // =====================================================================
  {
    id: "dharan-dbest",
    name: "D Best Coffee",
    city: "Dharan",
    district: "Sunsari",
    area: "Bhanu Chowk, Dharan Bazar",
    lat: 26.8124,
    lng: 87.2835,
    rating: 4.8,
    reviewsCount: 312,
    priceLevel: "रुरु",
    vibe: ["Specialty Coffee", "Work & Study Friendly", "Aesthetic & Cozy"],
    features: ["Specialty Beans", "Fast WiFi", "Power Outlets", "Air Conditioned"],
    signatureItem: "Himalayan Pour-over & Caramel Macchiato",
    foodHighlight: "Fresh Almond Croissant & Club Sandwich",
    weekendTip: "Grab a corner table by the window early Saturday morning for reading while smelling fresh roasts.",
    timing: "7:00 AM – 9:00 PM",
    phone: "+977 25-520111",
    instagram: "@dbestcoffeedharan",
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    description: "A sanctuary for true coffee purists in eastern Nepal. Serves single-origin organic Himalayan beans roasted to perfection."
  },
  {
    id: "dharan-station",
    name: "Coffee Station Dharan",
    city: "Dharan",
    district: "Sunsari",
    area: "Bhanu Chowk Central",
    lat: 26.8138,
    lng: 87.2842,
    rating: 4.7,
    reviewsCount: 420,
    priceLevel: "रुरु",
    vibe: ["Weekend Hangout / Live Vibe", "Specialty Coffee"],
    features: ["Outdoor Seating", "WiFi", "Cold Brew Bar"],
    signatureItem: "Spanish Iced Latte & Hazelnut Frappe",
    foodHighlight: "Crispy Peri-Peri Chicken Strips & Waffles",
    weekendTip: "Lively hub on Saturday afternoons; sit outdoors to enjoy the Dharan street energy and music.",
    timing: "7:30 AM – 9:30 PM",
    phone: "+977 25-525490",
    instagram: "@coffeestation_dharan",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    description: "One of Dharan's most iconic meeting points. Unwind with friend groups over frosted cold brews and delicious bites."
  },
  {
    id: "dharan-koich",
    name: "Koich Cafe & Restro",
    city: "Dharan",
    district: "Sunsari",
    area: "Putali Line, Dharan-4",
    lat: 26.8115,
    lng: 87.2821,
    rating: 4.6,
    reviewsCount: 290,
    priceLevel: "रु",
    vibe: ["Weekend Hangout / Live Vibe", "Aesthetic & Cozy"],
    features: ["Budget Friendly", "WiFi", "Youth Favorite"],
    signatureItem: "Thick Cold Coffee with Ice Cream",
    foodHighlight: "Famous Dharan Momo & Chicken Paratha Roll",
    weekendTip: "The best pocket-friendly hangout for college crews and weekend gossip over steamy momos and cold coffee.",
    timing: "10:00 AM – 8:30 PM",
    phone: "+977 9802720000",
    instagram: "@koich_cafe",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    description: "Beloved neighborhood gem in Putali Line famous for fusion snacks, creamy cold coffee, and vibrant local vibes."
  },
  {
    id: "dharan-levelup",
    name: "LevelUp Sunset Restro & Cafe",
    city: "Dharan",
    district: "Sunsari",
    area: "Vijayapur Hill Road",
    lat: 26.8245,
    lng: 87.2950,
    rating: 4.7,
    reviewsCount: 380,
    priceLevel: "रुरु",
    vibe: ["Scenic & Mountain Views", "Weekend Hangout / Live Vibe"],
    features: ["Mountain View", "Sunset Terrace", "Live Music", "Outdoor Seating"],
    signatureItem: "Iced Americano with Lemonade & Mochaccino",
    foodHighlight: "Crispy Chilly Pork / Sekuwa & Wood-fire Pizza",
    weekendTip: "Arrive around 4:45 PM on weekend evenings to witness breathtaking golden-hour vistas overlooking the entire Dharan valley.",
    timing: "11:00 AM – 10:00 PM",
    phone: "+977 9812345678",
    instagram: "@levelup_dharan",
    image: "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=800&q=80",
    description: "Perched high on the slopes toward Vijayapur, offering panoramic views of the hills and plains, cool breezes, and great weekend acoustic sessions."
  },
  {
    id: "ita-java",
    name: "Himalayan Java Coffee (Itahari)",
    city: "Itahari",
    district: "Sunsari",
    area: "Bhatbhateni Supermarket Complex",
    lat: 26.6645,
    lng: 87.2788,
    rating: 4.8,
    reviewsCount: 650,
    priceLevel: "रुरु",
    vibe: ["Specialty Coffee", "Work & Study Friendly", "Bakery & Desserts"],
    features: ["Signature Roast", "Air Conditioned", "WiFi", "Parking Space"],
    signatureItem: "Himalayan Java Honey Latte & Cold Brew",
    foodHighlight: "Baked Blueberry Cheesecake & Chicken Bagel",
    weekendTip: "The gold standard for coffee lovers in Itahari. Grab a seat after weekend shopping at Bhatbhateni.",
    timing: "7:00 AM – 9:30 PM",
    phone: "+977 25-580199",
    instagram: "@himalayanjava_itahari",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80",
    description: "Nepal’s premier international coffee pioneer brings its iconic roasting mastery, plush leather armchairs, and world-class bakes to Itahari."
  },
  {
    id: "ita-monk",
    name: "Monk and Punk Chyafe",
    city: "Itahari",
    district: "Sunsari",
    area: "Tarahara / Itahari outskirts",
    lat: 26.6920,
    lng: 87.2810,
    rating: 4.7,
    reviewsCount: 260,
    priceLevel: "रु",
    vibe: ["Aesthetic & Cozy", "Weekend Hangout / Live Vibe"],
    features: ["Bohemian Decor", "Art Exhibitions", "Board Games", "Floor Seating"],
    signatureItem: "Masala Matka Chai & Dirty Chai Latte",
    foodHighlight: "Wai Wai Sadeko & Crispy Cheesy Nachos",
    weekendTip: "Play board games (Catan, Jenga, Uno) with friends while sipping spiced tea in their rustic cushions corner.",
    timing: "10:00 AM – 9:00 PM",
    phone: "+977 9812903344",
    instagram: "@monkandpunkchyafe",
    image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=800&q=80",
    description: "Bohemian artistic chyafe bringing together youth, art displays, vintage posters, aromatic herbal teas, and great conversations."
  },

  // =====================================================================
  // 4. ILAM DISTRICT (Kanyam, Ilam Bazaar, Shree Antu)
  // =====================================================================
  {
    id: "ilam-kanyam",
    name: "Kanyam Cloud View Tea & Coffee Cafe",
    city: "Kanyam",
    district: "Ilam",
    area: "Kanyam Tea Estate Hilltop",
    lat: 26.8580,
    lng: 88.0720,
    rating: 4.9,
    reviewsCount: 890,
    priceLevel: "रु",
    vibe: ["Scenic & Mountain Views", "Specialty Coffee"],
    features: ["Spectacular Tea Garden Views", "Panoramic Terrace", "Fresh Orthodox Tea", "Photogenic"],
    signatureItem: "Fresh Organic First-Flush Orthodox Tea & Hill Drip Coffee",
    foodHighlight: "Hot Local Akabare Momo & Chhurpi Sticks",
    weekendTip: "Watch rolling clouds drift across emerald tea slopes while savoring piping-hot tea and spicy akabare momos!",
    timing: "6:00 AM – 7:30 PM",
    phone: "+977 27-540120",
    instagram: "@kanyam_views",
    image: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=800&q=80",
    description: "Perched atop the lush undulating tea estates of Kanyam. Breathe in crisp mountain air, surrounded by endless rows of green tea shrubs."
  },
  {
    id: "ilam-heritage",
    name: "Ilam Heritage Tea & Coffee House",
    city: "Ilam Bazaar",
    district: "Ilam",
    area: "Ilam Bazaar Central",
    lat: 26.9100,
    lng: 87.9270,
    rating: 4.7,
    reviewsCount: 340,
    priceLevel: "रु",
    vibe: ["Scenic & Mountain Views", "Aesthetic & Cozy"],
    features: ["Historic Wooden Architecture", "Local Tea Tasting", "Hillside Views"],
    signatureItem: "White Tea Infusion & Cinnamon Black Coffee",
    foodHighlight: "Traditional Ilam Khaja Set with Ghee & Chhurpi Achar",
    weekendTip: "Sample multiple artisan tea flushes guided by local tea masters right in historic Ilam Bazaar.",
    timing: "7:00 AM – 8:00 PM",
    phone: "+977 27-520112",
    instagram: "@ilamheritagecafe",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
    description: "Housed in a heritage wooden building, this charming spot is the spiritual home of eastern Nepal’s finest orthodox teas and local coffee."
  },
  {
    id: "ilam-antu",
    name: "Antu Valley Sunrise Cafe",
    city: "Shree Antu",
    district: "Ilam",
    area: "Antu Danda Viewpoint",
    lat: 26.9025,
    lng: 88.1150,
    rating: 4.8,
    reviewsCount: 420,
    priceLevel: "रु",
    vibe: ["Scenic & Mountain Views"],
    features: ["Mt. Kanchenjunga Sunrise View", "Open Air Deck", "Campfire Evenings"],
    signatureItem: "Ginger Honey Mountain Tea & Strong Black Coffee",
    foodHighlight: "Fresh Fried Local Trout & Hot Sel Roti",
    weekendTip: "Wake up before dawn on Sunday to sip hot coffee on the deck while the first golden sunlight touches Mt. Kanchenjunga!",
    timing: "5:00 AM – 8:00 PM",
    phone: "+977 9804567890",
    instagram: "@shreeantu_cafe",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80",
    description: "Famous throughout Nepal as the prime spot to greet the sunrise over the Himalayas, overlooking Nepal and Darjeeling valley."
  },

  // =====================================================================
  // 5. DHANKUTA DISTRICT (Bhedetar, Hile, Dhankuta Bazaar)
  // =====================================================================
  {
    id: "dhk-cloudnine",
    name: "Bhedetar Cloud Nine Cafe & Restro",
    city: "Bhedetar",
    district: "Dhankuta",
    area: "Bhedetar View Tower Ridge",
    lat: 26.8520,
    lng: 87.3230,
    rating: 4.8,
    reviewsCount: 760,
    priceLevel: "रुरु",
    vibe: ["Scenic & Mountain Views", "Weekend Hangout / Live Vibe"],
    features: ["Panoramic View Tower", "Chilly Hill Weather", "Fireplace", "Outdoor Balcony"],
    signatureItem: "Spiced Himalayan Hot Chocolate & Cinnamon Latte",
    foodHighlight: "Dharan-Style Pork Sekuwa & Piping Hot Thukpa",
    weekendTip: "Drive 25 minutes up from Dharan on Saturday for cool mist, cloud blanket views, and mouthwatering hot food.",
    timing: "7:00 AM – 9:00 PM",
    phone: "+977 26-620045",
    instagram: "@bhedetar_cloudnine",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    description: "High above the southern plains at 1,420m elevation. Often blanketed in poetic mountain fog, serving steamy coffee and famous hill appetizers."
  },
  {
    id: "dhk-charles",
    name: "Charles Point Hilltop Cafe",
    city: "Bhedetar",
    district: "Dhankuta",
    area: "Charles Point Peak, Bhedetar",
    lat: 26.8550,
    lng: 87.3270,
    rating: 4.7,
    reviewsCount: 390,
    priceLevel: "रु",
    vibe: ["Scenic & Mountain Views"],
    features: ["Historic Royal View", "360 Degree Panorama", "Open Sky Terrace"],
    signatureItem: "Hillside Ginger Tea & Nescafe Roast",
    foodHighlight: "Steamed Aloo Dum & Wai Wai Sadheko",
    weekendTip: "Named after Britain's King Charles who visited this exact viewpoint in 1980. The 360-degree photo spot is unmatched.",
    timing: "6:30 AM – 7:30 PM",
    phone: "+977 9811223344",
    instagram: "@charlespoint_bhedetar",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
    description: "Legendary hilltop lookout offering 360-degree panoramic sights of the Sapta Koshi river gorge on one side and Makalu/Everest ranges on clear days."
  },
  {
    id: "dhk-hile",
    name: "Hile Alpine Restro & Coffee",
    city: "Hile",
    district: "Dhankuta",
    area: "Hile Bazaar, Upper Dhankuta",
    lat: 27.0420,
    lng: 87.3290,
    rating: 4.7,
    reviewsCount: 290,
    priceLevel: "रुरु",
    vibe: ["Scenic & Mountain Views", "Aesthetic & Cozy"],
    features: ["Alpine Lodge Ambiance", "Wood Stove / Heating", "Authentic Tongba & Coffee"],
    signatureItem: "Hot Buttered Coffee & Authentic Millet Tongba",
    foodHighlight: "Hile Sukuti Fry & Traditional Tibetan Tingmo",
    weekendTip: "Experience authentic Eastern hill weather in crisp Hile. Sit beside the fireplace with a hot brew.",
    timing: "7:00 AM – 9:00 PM",
    phone: "+977 26-540022",
    instagram: "@hile_alpinerestro",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
    description: "Perched in the cool heights of Hile (1,900m). Warm alpine wooden interiors, crackling hearths, and robust coffees."
  },

  // =====================================================================
  // 6. PANCHTHAR DISTRICT (Phidim)
  // =====================================================================
  {
    id: "panch-blackbeans",
    name: "Black Beans Cafe & Bar",
    city: "Phidim",
    district: "Panchthar",
    area: "Phidim Bazaar Center",
    lat: 27.1510,
    lng: 87.7640,
    rating: 4.7,
    reviewsCount: 210,
    priceLevel: "रुरु",
    vibe: ["Weekend Hangout / Live Vibe", "Specialty Coffee"],
    features: ["Specialty Coffee", "Acoustic Nights", "WiFi", "Bar & Bites"],
    signatureItem: "Mountain Filter Coffee & Iced Caramel Latte",
    foodHighlight: "Crispy Chilly Chicken & Local Sukuti Fry",
    weekendTip: "The liveliest social meeting spot in Phidim for youths and travelers venturing on the Mid-Hill Highway.",
    timing: "8:00 AM – 9:30 PM",
    phone: "+977 24-520333",
    instagram: "@blackbeans_phidim",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80",
    description: "Phidim’s most popular coffee and hangout lounge, offering espresso drinks, tasty hill snacks, and acoustic weekend tunes."
  },
  {
    id: "panch-ikrusha",
    name: "Ikrusha Cafe",
    city: "Phidim",
    district: "Panchthar",
    area: "Hospital Chowk, Phidim",
    lat: 27.1530,
    lng: 87.7610,
    rating: 4.5,
    reviewsCount: 140,
    priceLevel: "रु",
    vibe: ["Aesthetic & Cozy"],
    features: ["Quiet Environment", "Local Coffee", "Quick Service"],
    signatureItem: "Strong Himalayan Milk Coffee & Lemon Tea",
    foodHighlight: "Fresh Fried Dumplings & Chowmein",
    weekendTip: "Cozy local eatery popular with locals for warm beverages on chilly hill mornings.",
    timing: "7:00 AM – 8:00 PM",
    phone: "+977 9812304958",
    instagram: "@ikrushacafe_phidim",
    image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=800&q=80",
    description: "Friendly neighborhood cafe in Phidim offering warm hospitality, piping hot coffee, and comfort snacks."
  },

  // =====================================================================
  // 7. TAPLEJUNG DISTRICT (Phungling Bazaar)
  // =====================================================================
  {
    id: "tap-poudel",
    name: "Poudel Coffee Ghar",
    city: "Phungling",
    district: "Taplejung",
    area: "Phungling Bazaar Central",
    lat: 27.3510,
    lng: 87.6710,
    rating: 4.8,
    reviewsCount: 310,
    priceLevel: "रु",
    vibe: ["Specialty Coffee", "Scenic & Mountain Views"],
    features: ["Famous Ghoteko Coffee", "Heritage Craft", "Pilgrim Favorite", "Pathibhara Transit"],
    signatureItem: "Authentic Hand-Whipped 'Ghoteko Coffee'",
    foodHighlight: "Homemade Malpa & Steamed Sel Roti",
    weekendTip: "Renowned across eastern Nepal for their hand-frother 'Ghoteko Coffee'. A mandatory stop before heading to Pathibhara Temple!",
    timing: "5:30 AM – 8:00 PM",
    phone: "+977 24-460123",
    instagram: "@poudelcoffee_taplejung",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    description: "Legendary Taplejung establishment revered by mountain trekkers and Pathibhara pilgrims for their rich, velvety hand-whipped frothy coffee."
  },
  {
    id: "tap-kabru",
    name: "Kabru Cafe & Restaurant",
    city: "Phungling",
    district: "Taplejung",
    area: "Upper Phungling Road",
    lat: 27.3540,
    lng: 87.6735,
    rating: 4.6,
    reviewsCount: 180,
    priceLevel: "रुरु",
    vibe: ["Scenic & Mountain Views", "Aesthetic & Cozy"],
    features: ["Brewed With Altitude", "Mountain Ridge View", "Kanchenjunga Gateway"],
    signatureItem: "High Altitude Aeropress & Cinnamon Black Tea",
    foodHighlight: "Yak Cheese Omelette & Local Millet Porridge",
    weekendTip: "Enjoy crisp alpine breezes and view dramatic ridges while savoring coffee brewed at high elevation.",
    timing: "6:30 AM – 8:30 PM",
    phone: "+977 24-460345",
    instagram: "@kabrucafe_taplejung",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80",
    description: "Famous for its motto 'Brewed With Altitude'. Serves altitude-grown Arabica to adventurers beginning their Kanchenjunga expedition."
  },

  // =====================================================================
  // 8. SANKHUWASABHA DISTRICT (Khandbari)
  // =====================================================================
  {
    id: "sankh-san",
    name: "San Coffee & Restro",
    city: "Khandbari",
    district: "Sankhuwasabha",
    area: "Pokhari Bazaar, Khandbari",
    lat: 27.3750,
    lng: 87.2060,
    rating: 4.8,
    reviewsCount: 260,
    priceLevel: "रुरु",
    vibe: ["Specialty Coffee", "Work & Study Friendly"],
    features: ["On-Site Roasted Beans", "Local Farmer Direct", "WiFi", "Arun Valley View"],
    signatureItem: "Freshly Roasted Khandbari Arabica Pour-over",
    foodHighlight: "Club Sandwiches & Crispy Buff Momo",
    weekendTip: "Beans are sourced directly from local organic farmers around Sankhuwasabha and roasted right before your eyes.",
    timing: "7:00 AM – 8:30 PM",
    phone: "+977 29-560410",
    instagram: "@sancoffee_khandbari",
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80",
    description: "A gem in Makalu’s gateway town of Khandbari. High-quality single origin coffee sourced from Sankhuwasabha's fertile slopes."
  },
  {
    id: "sankh-shisha",
    name: "Shisha Cafe & Restro",
    city: "Khandbari",
    district: "Sankhuwasabha",
    area: "Central Chowk, Khandbari",
    lat: 27.3730,
    lng: 87.2040,
    rating: 4.5,
    reviewsCount: 190,
    priceLevel: "रु",
    vibe: ["Weekend Hangout / Live Vibe"],
    features: ["Youth Hangout", "Music Lounge", "Evening Vibe"],
    signatureItem: "Iced Mochaccino & Fruit Coolers",
    foodHighlight: "Spicy Crispy Chicken Wings & Burgers",
    weekendTip: "The happening evening spot in town where local youths gather for drinks, music, and weekend relaxation.",
    timing: "9:00 AM – 9:30 PM",
    phone: "+977 9811092837",
    instagram: "@shishacafe_khandbari",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    description: "A trendy meeting spot right in town center, serving ice blended drinks, burgers, and comfort food."
  },

  // =====================================================================
  // 9. BHOJPUR DISTRICT (Bhojpur Bazaar)
  // =====================================================================
  {
    id: "bhoj-bihani",
    name: "Bihani Coffee House",
    city: "Bhojpur Bazaar",
    district: "Bhojpur",
    area: "Bhojpur Bazaar Central",
    lat: 27.1720,
    lng: 87.0450,
    rating: 4.6,
    reviewsCount: 160,
    priceLevel: "रु",
    vibe: ["Scenic & Mountain Views", "Aesthetic & Cozy"],
    features: ["Historic Hill Town", "Traditional Wooden Charm", "Mountain Arabica"],
    signatureItem: "Fresh Hill French Press Coffee & Ginger Tea",
    foodHighlight: "Famous Bhojpur Aloo Dum & Hot Kothey Momos",
    weekendTip: "Stroll through the cobblestone streets of historic Bhojpur and warm up inside Bihani with piping hot brews.",
    timing: "6:30 AM – 7:30 PM",
    phone: "+977 29-420115",
    instagram: "@bihanicoffee_bhojpur",
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    description: "Known throughout Bhojpur Bazaar for warm hospitality, fresh mountain-grown coffee, and a cozy retreat from the cool hill breeze."
  },
  {
    id: "bhoj-taksar",
    name: "Taksar Heritage Chyafe",
    city: "Taksar",
    district: "Bhojpur",
    area: "Historic Metalcraft Quarter, Taksar",
    lat: 27.1640,
    lng: 87.0510,
    rating: 4.7,
    reviewsCount: 130,
    priceLevel: "रु",
    vibe: ["Scenic & Mountain Views", "Aesthetic & Cozy"],
    features: ["Historic Bronze Era Site", "Authentic Teas & Coffee", "Artisan Culture"],
    signatureItem: "Spiced Brass-Pot Himalayan Tea & Black Coffee",
    foodHighlight: "Local Khaja Set with Chhurpi and Boiled Yam",
    weekendTip: "Sit in the ancient minting village of Taksar, famous for handmade Khukuris and bronze crafts, enjoying tea served in brass cups.",
    timing: "7:00 AM – 7:00 PM",
    phone: "+977 9801928374",
    instagram: "@taksarheritage_bhojpur",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
    description: "Immersed in the rich cultural heritage of Taksar, Bhojpur. Enjoy traditional teas and local hill coffee surrounded by artisan workshops."
  },

  // =====================================================================
  // 10. TERHATHUM DISTRICT (Myanglung & Basantapur)
  // =====================================================================
  {
    id: "terh-laligurans",
    name: "Laligurans Hilltop Cafe",
    city: "Myanglung",
    district: "Terhathum",
    area: "Myanglung Bazaar Top",
    lat: 27.1350,
    lng: 87.4420,
    rating: 4.7,
    reviewsCount: 180,
    priceLevel: "रु",
    vibe: ["Scenic & Mountain Views", "Aesthetic & Cozy"],
    features: ["Capital of Rhododendrons", "Valley Lookout", "Organic Hill Beans"],
    signatureItem: "Rhododendron Honey Herbal Tea & Hill Coffee",
    foodHighlight: "Terhathum Dhaka-Woven Decor & Steamed Momos",
    weekendTip: "Visit during rhododendron blossom season (March-May) when hills turn crimson red; savor local flower honey tea!",
    timing: "6:30 AM – 7:30 PM",
    phone: "+977 26-460118",
    instagram: "@laligurans_terhathum",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    description: "Located in the heart of Myanglung, famous for traditional Dhaka textiles and surrounded by Terhathum’s legendary rhododendron forests."
  },
  {
    id: "terh-basantapur",
    name: "Basantapur Ridge Coffee House",
    city: "Basantapur",
    district: "Terhathum",
    area: "Basantapur Bazaar Ridge",
    lat: 27.1300,
    lng: 87.3980,
    rating: 4.6,
    reviewsCount: 220,
    priceLevel: "रु",
    vibe: ["Scenic & Mountain Views"],
    features: ["Tinjure Milke Jaljale Route", "Cool Mountain Fog", "Trekker Hub"],
    signatureItem: "Hot Buttered Black Coffee & Ginger Cardamom Tea",
    foodHighlight: "Spicy Sukuti Sadeko & Hot Thukpa Soup",
    weekendTip: "The primary gateway for the Tinjure-Milke-Jaljale (TMJ) rhododendron trek. Grab hot coffee while waiting for transport.",
    timing: "6:00 AM – 8:00 PM",
    phone: "+977 26-440055",
    instagram: "@basantapur_coffee",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
    description: "Perched on the chilly transit ridge of Basantapur, serving piping hot beverages and warm mountain meals to trekkers."
  },

  // =====================================================================
  // 11. UDAYAPUR DISTRICT (Gaighat)
  // =====================================================================
  {
    id: "uday-doko",
    name: "Doko Bakery and Cafe",
    city: "Gaighat",
    district: "Udayapur",
    area: "Main Chowk, Gaighat (Triyuga)",
    lat: 26.7930,
    lng: 86.6970,
    rating: 4.7,
    reviewsCount: 320,
    priceLevel: "रुरु",
    vibe: ["Bakery & Desserts", "Aesthetic & Cozy"],
    features: ["Fresh Bakery", "Air Conditioned", "Specialty Shakes", "WiFi"],
    signatureItem: "Hazelnut Cappuccino & Oreo Crunch Frappe",
    foodHighlight: "Fresh Chocolate Truffle Cake & Crispy Burgers",
    weekendTip: "Gaighat’s favorite spot for weekend birthday celebrations and casual coffee catchups.",
    timing: "7:30 AM – 9:00 PM",
    phone: "+977 35-420888",
    instagram: "@dokocafe_gaighat",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    description: "The most popular modern cafe and bakery in Udayapur's administrative hub, serving freshly baked pastries and espresso."
  },
  {
    id: "uday-cakecafe",
    name: "Gaighat Cake Parlour & Cafe",
    city: "Gaighat",
    district: "Udayapur",
    area: "College Road, Gaighat",
    lat: 26.7915,
    lng: 86.6950,
    rating: 4.5,
    reviewsCount: 210,
    priceLevel: "रु",
    vibe: ["Bakery & Desserts", "Weekend Hangout / Live Vibe"],
    features: ["Custom Pastries", "Youth Friendly", "Quick Snacks"],
    signatureItem: "Cold Coffee with Vanilla Float & Brownie Shake",
    foodHighlight: "Pizza Slices & Spicy Chicken Rolls",
    weekendTip: "Great casual hangout for students and families in Gaighat seeking sweet weekend desserts.",
    timing: "8:00 AM – 8:30 PM",
    phone: "+977 35-421200",
    instagram: "@gaighatcakeparlour",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    description: "Beloved sweet treats shop in Gaighat known for delicious customized cakes, thick milkshakes, and hot cappuccino."
  },

  // =====================================================================
  // 12. KHOTANG DISTRICT (Diktel & Halesi)
  // =====================================================================
  {
    id: "khot-diktel",
    name: "Diktel Cozy Coffee House",
    city: "Diktel",
    district: "Khotang",
    area: "Diktel Bazaar Central",
    lat: 27.2140,
    lng: 86.7900,
    rating: 4.6,
    reviewsCount: 175,
    priceLevel: "रु",
    vibe: ["Aesthetic & Cozy", "Scenic & Mountain Views"],
    features: ["Mid-Hill Retreat", "Warm Wooden Interiors", "Local Snacks"],
    signatureItem: "Freshly Ground Hill Arabica & Spiced Masala Tea",
    foodHighlight: "Steamed Buff Momos & Khotang Special Gundruk Sadeko",
    weekendTip: "The leading social cafe in Diktel Bazaar where government officials, teachers, and youths gather for evening coffee.",
    timing: "7:00 AM – 8:00 PM",
    phone: "+977 36-420188",
    instagram: "@diktelcoffee",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    description: "A cozy mountain cafe nestled in Diktel, offering comforting warm drinks and traditional eastern hill snacks."
  },
  {
    id: "khot-halesi",
    name: "Halesi Peace Cafe & Restro",
    city: "Halesi",
    district: "Khotang",
    area: "Near Halesi Maratika Cave",
    lat: 27.1890,
    lng: 86.6180,
    rating: 4.7,
    reviewsCount: 280,
    priceLevel: "रु",
    vibe: ["Scenic & Mountain Views", "Aesthetic & Cozy"],
    features: ["Pilgrimage Gateway", "Peaceful Courtyard", "Tibetan Butter Tea & Coffee"],
    signatureItem: "Tibetan Salt Butter Tea (Po Cha) & Hot Black Coffee",
    foodHighlight: "Vegetarian Thukpa & Steamed Tingmo with Lentils",
    weekendTip: "Located right outside the sacred Halesi Maratika Cave (the 'Pashupatinath of the East'). Highly peaceful sanctuary.",
    timing: "6:00 AM – 8:00 PM",
    phone: "+977 36-410022",
    instagram: "@halesipeacecafe",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
    description: "Serene cafe serving pilgrims and travelers visiting Halesi Mahadev Cave with traditional Tibetan butter teas, local coffee, and vegetarian fare."
  },

  // =====================================================================
  // 13. OKHALDHUNGA DISTRICT (Okhaldhunga Bazaar & Rumjatar)
  // =====================================================================
  {
    id: "okh-rose",
    name: "Rose Restro & Cafe",
    city: "Okhaldhunga Bazaar",
    district: "Okhaldhunga",
    area: "Okhaldhunga Bazaar Center",
    lat: 27.3180,
    lng: 86.5050,
    rating: 4.5,
    reviewsCount: 160,
    priceLevel: "रु",
    vibe: ["Weekend Hangout / Live Vibe"],
    features: ["District Headquarters", "Comfortable Seating", "Traveler Friendly"],
    signatureItem: "Warm Milk Coffee & Fresh Lemon Ginger Honey",
    foodHighlight: "Crispy Fried Chicken & Buff Sukuti Sadeko",
    weekendTip: "The most comfortable dining and coffee spot in Okhaldhunga headquarters for weekend evenings.",
    timing: "7:30 AM – 9:00 PM",
    phone: "+977 37-520234",
    instagram: "@roserestro_okhaldhunga",
    image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80",
    description: "A welcoming restaurant and cafe in Okhaldhunga Bazaar offering hot coffee, hearty hill meals, and a friendly vibe."
  },
  {
    id: "okh-rumjatar",
    name: "Rumjatar Runway Cafe & Bakery",
    city: "Rumjatar",
    district: "Okhaldhunga",
    area: "Rumjatar Airport Plateau",
    lat: 27.3030,
    lng: 86.5500,
    rating: 4.6,
    reviewsCount: 140,
    priceLevel: "रु",
    vibe: ["Scenic & Mountain Views"],
    features: ["Airport Tableland View", "Famous Rumjatar Wool Rug Heritage", "Fresh Bakes"],
    signatureItem: "Drip Coffee & Local Goat Milk Tea",
    foodHighlight: "Fresh Fried Sel Roti & Potato Curry",
    weekendTip: "Located on the majestic flat tableland plateau of Rumjatar; watch mountain planes take off while sipping hot tea.",
    timing: "6:30 AM – 7:30 PM",
    phone: "+977 9819283746",
    instagram: "@rumjatarcafe",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
    description: "Overlooking the broad plateau of Rumjatar, serving trekkers, pilots, and locals with comforting bakes and coffee."
  },

  // =====================================================================
  // 14. SOLUKHUMBU DISTRICT (Namche Bazaar & Lukla - World Famous Everest Cafes)
  // =====================================================================
  {
    id: "solu-sherpa",
    name: "Sherpa Barista Bakery & Cafe",
    city: "Namche Bazaar",
    district: "Solukhumbu",
    area: "Namche Amphitheatre (3,440m)",
    lat: 27.8055,
    lng: 86.7115,
    rating: 4.9,
    reviewsCount: 920,
    priceLevel: "रुरु",
    vibe: ["Specialty Coffee", "Scenic & Mountain Views", "Bakery & Desserts"],
    features: ["Illy Specialty Coffee", "High Elevation Roasts", "Fast Satellite WiFi", "Fireplace Lounge"],
    signatureItem: "Illy Double Espresso & Hot Caramel Macchiato",
    foodHighlight: "Fresh Warm Himalayan Apple Pie & Cinnamon Rolls",
    weekendTip: "The most famous coffee haven on the entire Everest Base Camp route. Sit beside the roaring fireplace with warm apple pie!",
    timing: "6:00 AM – 9:00 PM",
    phone: "+977 38-540112",
    instagram: "@sherpabarista_namche",
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80",
    description: "World-renowned alpine cafe in the Sherpa capital of Namche (3,440m). Premium Italian Illy espresso, legendary apple pie, and Himalayan mountaineers."
  },
  {
    id: "solu-namchebakery",
    name: "Namche Bakery & Cafe",
    city: "Namche Bazaar",
    district: "Solukhumbu",
    area: "Main Market Stairway, Namche",
    lat: 27.8065,
    lng: 86.7130,
    rating: 4.8,
    reviewsCount: 780,
    priceLevel: "रुरु",
    vibe: ["Bakery & Desserts", "Scenic & Mountain Views"],
    features: ["Oldest Bakery in Khumbu", "Real Espresso", "Trekker Gathering Hub"],
    signatureItem: "Cafe Mocha & Hot Spiced Rum Punch",
    foodHighlight: "Decadent Chocolate Fudge Cake & Yak Cheese Pizza",
    weekendTip: "A rite of passage for mountaineers. Grab their chocolate brownie and watch peaks like Kongde Ri from the window.",
    timing: "6:30 AM – 9:00 PM",
    phone: "+977 38-540034",
    instagram: "@namchebakery",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    description: "The historic pioneer of high-altitude alpine baking in the Khumbu region, treating Everest climbers to world-class coffee and pastries since 1990."
  },
  {
    id: "solu-cafe4410",
    name: "Cafe 4410 Lukla",
    city: "Lukla",
    district: "Solukhumbu",
    area: "Lukla Airport Runway (2,860m)",
    lat: 27.6865,
    lng: 86.7290,
    rating: 4.8,
    reviewsCount: 540,
    priceLevel: "रुरु",
    vibe: ["Scenic & Mountain Views", "Weekend Hangout / Live Vibe"],
    features: ["Runway View Deck", "Specialty Barista", "Live Music", "Trekker Celebration Hub"],
    signatureItem: "Everest Highland Espresso & Irish Coffee",
    foodHighlight: "Handmade Sourdough Pizzas & Burgers",
    weekendTip: "Watch Twin Otter airplanes land on Lukla’s dramatic cliffside runway right from your cafe table with celebratory Irish coffee!",
    timing: "6:00 AM – 10:00 PM",
    phone: "+977 38-550188",
    instagram: "@cafe4410lukla",
    image: "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=800&q=80",
    description: "Lukla's premier cafe and celebration lounge right beside Tenzing-Hillary Airport, where climbers and trekkers celebrate Everest journeys."
  }
];

// District Metadata for all 14 Districts of Koshi Province
const KOSHI_DISTRICTS = [
  { id: "All", name: "All 14 Districts", count: KOSHI_CAFES.length, icon: "✨" },
  { id: "Birtamod-Special", name: "Birtamod Hub (Jhapa)", count: KOSHI_CAFES.filter(c => c.city === "Birtamod").length, icon: "⭐" },
  { id: "Jhapa", name: "Jhapa", count: KOSHI_CAFES.filter(c => c.district === "Jhapa").length, icon: "🌴" },
  { id: "Morang", name: "Morang (Biratnagar)", count: KOSHI_CAFES.filter(c => c.district === "Morang").length, icon: "🏙️" },
  { id: "Sunsari", name: "Sunsari (Dharan/Itahari)", count: KOSHI_CAFES.filter(c => c.district === "Sunsari").length, icon: "☕" },
  { id: "Ilam", name: "Ilam", count: KOSHI_CAFES.filter(c => c.district === "Ilam").length, icon: "🌱" },
  { id: "Dhankuta", name: "Dhankuta & Bhedetar", count: KOSHI_CAFES.filter(c => c.district === "Dhankuta").length, icon: "☁️" },
  { id: "Panchthar", name: "Panchthar (Phidim)", count: KOSHI_CAFES.filter(c => c.district === "Panchthar").length, icon: "⛰️" },
  { id: "Taplejung", name: "Taplejung", count: KOSHI_CAFES.filter(c => c.district === "Taplejung").length, icon: "🏔️" },
  { id: "Sankhuwasabha", name: "Sankhuwasabha (Khandbari)", count: KOSHI_CAFES.filter(c => c.district === "Sankhuwasabha").length, icon: "🍃" },
  { id: "Bhojpur", name: "Bhojpur", count: KOSHI_CAFES.filter(c => c.district === "Bhojpur").length, icon: "🗡️" },
  { id: "Terhathum", name: "Terhathum", count: KOSHI_CAFES.filter(c => c.district === "Terhathum").length, icon: "🌺" },
  { id: "Udayapur", name: "Udayapur (Gaighat)", count: KOSHI_CAFES.filter(c => c.district === "Udayapur").length, icon: "🌾" },
  { id: "Khotang", name: "Khotang (Diktel/Halesi)", count: KOSHI_CAFES.filter(c => c.district === "Khotang").length, icon: "🕉️" },
  { id: "Okhaldhunga", name: "Okhaldhunga", count: KOSHI_CAFES.filter(c => c.district === "Okhaldhunga").length, icon: "🏞️" },
  { id: "Solukhumbu", name: "Solukhumbu (Everest/Namche)", count: KOSHI_CAFES.filter(c => c.district === "Solukhumbu").length, icon: "🏔️" }
];
